controller_manager:
  ros__parameters:
    update_rate: 100
    controllers:
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
        joints:
          - body_to_arm1
          - arm1_to_arm2
          - arm2_to_bucket
        gains:
          body_to_arm1:
            p: 100.0
            i: 0.01
            d: 10.0
          arm1_to_arm2:
            p: 100.0
            i: 0.01
            d: 10.0
          arm2_to_bucket:
            p: 100.0
            i: 0.01
            d: 10.0
        state_publish_rate: 50
        command_interfaces:
          - position
        action_monitor_rate: 10
